worker:
  name: raindrop
  server:
    port: 8080
    webContext: ccl-jettyserver/src/main/webapp
  rpcServer:
    host: 127.0.0.1:8880

database:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull
  username: root
  password: "123456"
  maxIdle: 5
  maxActive: 100

zookeeper:
  server:
    host: 127.0.0.1:2181